<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework></TargetFramework>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <RootNamespace>Dloizides.Testing</RootNamespace>
    <PackageId>Dloizides.Testing</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" Version="8.0.7" />
    <PackageReference Include="Testcontainers.PostgreSql" Version="4.15.0" />
    <PackageReference Include="xunit.extensibility.core" Version="2.9.3" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Dloizides.Testing.Tests" />
  </ItemGroup>

</Project>
